const JOB_SUB_CATEGORIES = {
  information_technology: [
    "Software Development",
    "Web Development",
    "Data Analysis",
    "Cybersecurity",
    "DevOps",
  ],
  marketing_and_advertising: [
    "Digital Marketing",
    "SEO/SEM Specialists",
    "Content Management",
    "Branding",
    "Market Research",
  ],
  sales_and_business_development: [
    "Corporate Sales",
    "Account Management",
    "Lead Generation",
    "E-commerce",
    "B2B Sales",
  ],
  finance_and_accounting: [
    "Financial Analysts",
    "Investment Management",
    "Auditors",
    "Accountants",
    "Tax Specialists",
  ],
  manufacturing_and_engineering: [
    "Mechanical Engineers",
    "Electrical Engineers",
    "Automation Specialists",
    "Production Managers",
    "Design Engineers",
  ],
  healthcare_and_medicine: [
    "Physicians Nurses",
    "Pharmacists",
    "Physical Therapists",
    "Lab Technicians",
  ],
  education_and_research: [
    "Teachers",
    "University Professors",
    "Research Scientists",
    "Lab Assistants",
    "Tutors",
  ],
  logistics_and_transportation: [
    "Logistics Coordinators",
    "Drivers",
    "Supply Chain Managers",
    " Freight Forwarders",
    "Couriers",
  ],
  customer_support: [
    "Customer Service Representatives",
    "Technical Support",
    "Call Center Operators",
    "IT Helpdesk",
  ],
  creative_professions: [
    "Graphic Designers",
    "Photographers",
    "Copywriters",
    "Editors",
    "Videographers",
  ],
  administrative_roles: [
    "Secretaries",
    "Office Administrators",
    "Office Managers",
    "Executive Assistants",
  ],
  tourism_and_hospitality: [
    "Tour Guides",
    "Travel Agents",
    "Receptionists",
    "Chefs",
    "Waitstaff",
  ],
  retail: ["Sales Assistants", "Cashiers", "Merchandisers", "Store Managers"],
  legal: ["Lawyers", "Notaries", "Legal Advisors", "Contract Specialists"],
  construction_and_real_estate: [
    "Architects",
    "Civil Engineers",
    "Realtors",
    "Surveyors",
    "Construction Workers",
  ],
  energy_and_environment: [
    "Energy Specialists",
    "Environmental Scientists",
    "Renewable Energy Experts",
    "Geologists",
    "Geophysicists",
  ],
  arts_and_entertainment: [
    "Musicians",
    "Actors",
    "Artists",
    "Event Planners",
    "Dancers",
  ],
  agriculture: [
    "Farmers",
    "Agronomists",
    "Veterinarians",
    "Agricultural Technicians",
    "Farm Workers",
  ],
  human_resources_and_recruitment: [
    "Recruiters",
    "HR Managers",
    "Training Specialists",
    "Talent Acquisition Consultants",
  ],
  industrial_design_and_fashion: [
    "Fashion Designers",
    "Textile Experts",
    "Industrial Designers",
    "Apparel Technicians",
  ],
  telecommunications: [
    "Network Engineers",
    "Telecommunications Technicians",
    "System Administrators",
    "VoIP Specialists",
  ],
  government_and_public_sector: [
    "Civil Servants",
    "Policy Analysts",
    "Public Health Workers",
    "Urban Planners",
  ],
  sports_and_fitness: [
    "Personal Trainers",
    "Sports Coaches",
    "Physiotherapists",
    "Nutritionists",
  ],
  security_and_law_enforcement: [
    "Security Guards",
    "Private Investigators",
    "Cybercrime Analysts",
  ],
  media_and_journalism: [
    "Journalists",
    "News Anchors",
    "Media Producers",
    "Social Media Managers",
  ],
  food_and_beverage: [
    "Bakers",
    "Baristas",
    "Bartenders",
    "Restaurant Managers",
  ],
  transport_and_aviation: [
    "Pilots",
    "Flight Attendants",
    "Air Traffic Controllers",
    "Logistics Managers",
  ],
  non_profit_and_ngos: [
    "Fundraising Specialists",
    "Program Managers",
    "Volunteer Coordinators",
    "Community Organizers",
  ],
  beauty_and_wellness: [
    "Hair Stylists",
    "Makeup Artists",
    "Massage Therapists",
    "Spa Managers",
  ],
  real_estate_and_property_management: [
    "Property Managers",
    "Leasing Agents",
    "Real Estate Appraisers",
    "Land Surveyors",
  ],
  automotive_industry: [
    "Mechanics",
    "Automotive Engineers",
    "Car Sales Consultants",
    "Quality Inspectors",
  ],
  chemicals_and_pharmaceuticals: [
    "Chemists",
    "Pharmacologists",
    "Lab Researchers",
    "Quality Control Specialists",
  ],
  event_management: [
    "Wedding Planners",
    "Conference Coordinators",
    "Stage Managers",
    "Sound and Light Technicians",
  ],
  luxury_and_fashion: [
    "Jewelry Designers",
    "Luxury Brand Managers",
    "Fashion Stylists",
    "Visual Merchandisers",
  ],
  cleaning_and_maintenance: [
    "Janitors",
    "Housekeepers",
    "Maintenance Technicians",
    "HVAC Specialists",
  ],
  pets_and_animal_care: [
    "Veterinarians",
    "Animal Trainers",
    "Pet Sitters",
    "Zookeepers",
  ],
  renewable_energy: [
    "Solar Panel Technicians",
    "Wind Turbine Engineers",
    "Energy Policy Analysts",
    "Sustainability Consultants",
  ],
  gaming_and_esports: [
    "Game Designers",
    "Game Testers",
    "Esports Players",
    "Streamers",
    "Community Managers",
  ],
  robotics_and_ai: [
    "Robotics Engineers",
    "Machine Learning Specialists",
    "AI Trainers",
    "Data Scientists",
    "AI Ethics Consultants",
  ],
  architecture_and_urban_design: [
    "Landscape Architects",
    "Urban Designers",
    "CAD Technicians",
    "Building Information Modelers (BIM Specialists)",
  ],
  space_and_aerospace: [
    "Astronauts",
    "Aerospace Engineers",
    "Satellite Technicians",
    "Space Operations Specialists",
  ],
  environment_and_sustainability: [
    "Environmental Consultants",
    "Waste Management Specialists",
    "Renewable Energy Installers",
    "Ecologists",
  ],
  cryptocurrency_and_blockchain: [
    "Blockchain Developers",
    "Crypto Traders",
    "Smart Contract Developers",
    "NFT Specialists",
  ],
  arts_and_crafts: [
    "Sculptors",
    "Ceramic Artists",
    "Glassblowers",
    "Textile Artists",
  ],
  performing_arts: [
    "Theater Directors",
    "Choreographers",
    "Stage Performers",
    "Opera Singers",
  ],
  social_services: [
    "Social Workers",
    "Case Managers",
    "Addiction Counselors",
    "Community Health Workers",
  ],
  photography_and_videography: [
    "Drone Operators",
    "Photo Editors",
    "Video Producers",
    "Documentary Makers",
  ],
  mining_and_geology: [
    "Mining Engineers",
    "Geologists",
    "Mineralogists",
    "Drilling Technicians",
  ],
  agritech_and_food_technology: [
    "Agritech Specialists",
    "Food Scientists",
    "Hydroponics Technicians",
    "Quality Assurance Experts",
  ],
  education_technology: [
    "Online Course Developers",
    "EdTech Product Managers",
    "Learning Experience Designers",
    "Instructional Technologists",
  ],
  handcrafts_and_trades: [
    "Carpenters",
    "Electricians",
    "Plumbers",
    "Blacksmiths",
  ],
  science_and_research: [
    "Astrophysicists",
    "Geneticists",
    "Marine Biologists",
    "Quantum Physicists",
  ],
  insurance_and_risk_management: [
    "Underwriters",
    "Claims Adjusters",
    "Actuaries",
    "Risk Analysts",
  ],
  entertainment_and_media_production: [
    "Film Directors",
    "Scriptwriters",
    "Animators",
    "Sound Engineers",
  ],
  fashion_and_textile: [
    "Pattern Makers",
    "Textile Technologists",
    "Fashion Buyers",
    "Trend Forecasters",
  ],
  childcare_and_education: [
    "Early Childhood Educators",
    "Nannies",
    "Educational Counselors",
    "Special Needs Assistants",
  ],
};

export default JOB_SUB_CATEGORIES;
